### ISSUE TITLE
Does not play well with koa-router

### ISSUE THREAD

**Issue by vanthome** [kudos/koa-websocket#20]
When I mount the WS endpoint with [koa-router](https://github.com/alexmingoia/koa-router/tree/master) I'm getting this exception when I'm trying to establish a WS connection with a proper client:

```
TypeError: Middleware must be composed of functions!
    at compose (/graphql-dataloader-boilerplate/node_modules/koa-compose/index.js:25:41)
    at KoaWebSocketServer.onConnection (/graphql-dataloader-boilerplate/node_modules/koa-websocket/index.js:27:22)
    at emitOne (events.js:96:13)
    at WebSocketServer.emit (events.js:188:7)
    at /graphql-dataloader-boilerplate/node_modules/ws/lib/WebSocketServer.js:91:14
    at completeHybiUpgrade2 (/graphql-dataloader-boilerplate/node_modules/ws/lib/WebSocketServer.js:284:5)
    at completeHybiUpgrade1 (/graphql-dataloader-boilerplate/node_modules/ws/lib/WebSocketServer.js:309:13)
    at WebSocketServer.handleHybiUpgrade (/graphql-dataloader-boilerplate/node_modules/ws/lib/WebSocketServer.js:337:3)
    at WebSocketServer.handleUpgrade (/graphql-dataloader-boilerplate/node_modules/ws/lib/WebSocketServer.js:173:26)
    at Server.WebSocketServer._onServerUpgrade (/graphql-dataloader-boilerplate/node_modules/ws/lib/WebSocketServer.js:89:12)
    at emitThree (events.js:116:13)
    at Server.emit (events.js:194:7)
    at onParserExecuteCommon (_http_server.js:409:14)
    at HTTPParser.onParserExecute (_http_server.js:377:5)
```

The integration is very basic like so:

```
app.ws.use(router.all('/ws', function(ctx) {
  ctx.websocket.on('message', (message) => {
    console.log(message);
  });
}));

app
  .use(router.routes())
  .use(router.allowedMethods());
```

Everything is koa 2.0.0 stuff.
I debuged it and the reason is that koa-compose complains that the router middleware is not a function but an object. Any idea what is to blame for that?

**Comment by shellscape** [comment]
I'd like to see some improvement in this area too.

**Comment by azhang** [comment]
```
app.ws.use(router.all('/ws', function (ctx) {
  ctx.websocket.on('message', function(message) {
    ctx.websocket.send('HELLOOO');
    console.log('onmessage', message);
  });
}).routes()); // .routes() is what converts this `router` object to koa2 middleware.
```

**Comment by kudos** [comment]
I don't use `koa-router` at all, so any improvements to the examples or readme are welcome :) It looks like @azhang has solved this.
