### ISSUE TITLE
How to add a '404' handler?

### ISSUE THREAD

**Issue by stefanb2** [kudos/koa-websocket#34]
I mounted WebSockets into my application using koa-websocket@4 and koa-router@7 under the routes `/xyz/...`. As long as only try to to connect with my WebSocket client to an implemented route, everything is fine. But when I try e.g. to connect to `/xyz/notimplemented` the client simply hangs.

So I thought "OK, I need to add a '404' middleware for WebSockets too" and started off with the standard Koa approach. But that just causes nasty back traces being logged on the server side (due to the `catch( debug() )` clause in the `'connection'` event handler) and leaves the client hanging:
```javascript
app.ws.use(router.routes())
      .use(router.allowedMethods());
app.ws.use(ctx => {
    ctx.throw(404, `route '${ctx.url}' not implemented`);
});
```
After a lot of head-scratching and trial & error I came up with the following, which makes sure the client exits nicely (the 4004 is *not* a typo) and reduces the log entry on the server side to one line:
```javascript
app.ws.use(ctx => {
    ctx.websocket.close(4004, `ERROR: route '${ctx.url}' is not implemented`);
    return Promise.reject(`route '${ctx.url}' is not implemented`);
});
```

If I comment out the `return Promise.reject(...);` line in the code above, then the server log shows:
```log
  koa:websockets TypeError: Cannot read property 'statusCode' of undefined
  koa:websockets     at Object.get status [as status] (.../node_modules/koa/lib/response.js:72:21)
  koa:websockets     at Object.status (.../node_modules/delegates/index.js:72:24)
  koa:websockets     at .../node_modules/koa-router/lib/router.js:409:16
  koa:websockets     at <anonymous>
  koa:websockets     at process._tickCallback (internal/process/next_tick.js:188:7) +4ms
```
which as far as I can tell is caused by the koa-websocket context being incomplete (it is missing a response object) and Koa barfs on it when the context is passed back up to it :-/

I can live with my solution, but I'm wondering if I'm missing something or should this be considered a bug/missing feature in koa-websocket?

**Comment by stefanb2** [comment]
The correct solution is to add a catch-all route handler. Example code included in PR #35.
