### ISSUE TITLE
how long will this.websocket alive

### ISSUE THREAD

**Issue by xhacker5000** [kudos/koa-websocket#7]
I save ``` this.websocket ```  on message like this

```javascript

var some_container = {};
this.websocket.on('message', function(message) {
       some_container.websocket = this.websocket
}.bind(this));
```

and I want use this websocket for sometime

then I call like this 

```javascript 
    some_container.websocket.send("test str");
```

then will show some error like 

```
  Error: not opened
      at WebSocket.send (/data/order-server-admin/node_modules/koa-websocket/node_modules/ws/lib/WebSocket.js:218:16)
      at Object.onlineStoreManager.noticeStoreOrder (/data/order-server-admin/lib/middleware/online_store_manager.js:75:13)
      at Object.PickingController.startPicking (/data/order-server-admin/lib/controllers/picking_controller.js:344:23)
      at GeneratorFunctionPrototype.next (native)
      at onFulfilled (/data/order-server-admin/node_modules/koa/node_modules/co/index.js:64:19)
      at in_the_handler (/data/order-server-admin/node_modules/mongoose/node_modules/mpromise/lib/promise.js:237:18)
      at process._tickCallback (node.js:355:11)
```

**Comment by kudos** [comment]
It's your code's job to check whether the client is still connected, there is no standard length of time it will stay connected, it could be 1 second, it could be days.

I appreciate your interest in this project, but questions like this will be better answered over at [StackOverflow](https://stackoverflow.com/).
